# Generated by Django 2.2.12 on 2020-05-06 18:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_name', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=18)),
                ('coverage_area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, srid=4326)),
                ('address', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
