# Generated by Django 2.2.12 on 2020-05-06 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='document',
        ),
    ]
