# Generated by Django 2.2.12 on 2020-05-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_partner_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='coverage_area',
            new_name='coverageArea',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='owner_name',
            new_name='ownerName',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='trading_name',
            new_name='tradingName',
        ),
    ]
